# Generated by Django 5.2.13 on 2026-04-22 18:13

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('nom_article', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('famille', models.CharField(choices=[('MP', 'MP'), ('PF', 'PF'), ('SPF', 'SPF'), ('P.RECH', 'P.RECH'), ('consommable', 'consommable')], max_length=50)),
                ('sous_famille', models.CharField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('unite_mesure', models.CharField(max_length=20)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('disponible', 'disponible'), ('bloqué', 'bloqué'), ('en contrôle', 'en contrôle'), ('réservé', 'réservé')], default='disponible', max_length=20)),
                ('seuil_securite', models.IntegerField()),
                ('classe_abc', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=1)),
                ('methode_valorisation', models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('CMP', 'CMP')], default='FIFO', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.CharField(default='Système', max_length=100)),
                ('type_action', models.CharField(max_length=50)),
                ('table_affectee', models.CharField(max_length=100)),
                ('id_entite_affectee', models.IntegerField(blank=True, null=True)),
                ('details_modifications', models.TextField(blank=True, null=True)),
                ('details_simplifies', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Historique d'Action",
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Responsable_magasin', 'Responsable Magasin'), ('magasinier', 'Magasinier'), ('Responsable_Audit', 'Responsable_Audit')], default='magasinier', max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id_emplacement', models.AutoField(primary_key=True, serialize=False)),
                ('zone_physique', models.CharField(choices=[('préparation', 'préparation'), ('stockage', 'stockage'), ('retours', 'retours')], max_length=50)),
                ('rack', models.IntegerField()),
                ('etagere', models.CharField(max_length=50)),
                ('capacite_max', models.IntegerField(default=0)),
                ('capacite_actuelle', models.IntegerField(default=0)),
                ('id_article', models.ForeignKey(blank=True, db_column='id_article', null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_app.article')),
            ],
        ),
        migrations.CreateModel(
            name='Historique_Classification_ABC',
            fields=[
                ('id_historique', models.AutoField(primary_key=True, serialize=False)),
                ('ancienne_classe', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('nouvelle_classe', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('date_changement', models.DateField()),
                ('id_article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, to='stock_app.article')),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id_inventaire', models.AutoField(primary_key=True, serialize=False)),
                ('date_inventaire', models.DateField()),
                ('type_inventaire', models.CharField(choices=[('fixe', 'fixe'), ('permanent', 'permanent'), ('tournant', 'tournant')], max_length=30)),
                ('statut_inventaire', models.CharField(max_length=30)),
                ('documents_reglementaires', models.CharField(blank=True, max_length=100, null=True)),
                ('articles_a_inventorier', models.ManyToManyField(related_name='inventaires_programmes', to='stock_app.article', verbose_name='Articles à inventorier')),
                ('id_responsable', models.ForeignKey(db_column='id_responsable', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id_lot', models.AutoField(primary_key=True, serialize=False)),
                ('date_peremption', models.DateField()),
                ('statut', models.CharField(choices=[('disponible', 'disponible'), ('bloqué', 'bloqué'), ('réservé', 'réservé'), ('en contrôle', 'en contrôle')], default='disponible', max_length=20)),
                ('proche', models.IntegerField(choices=[(1, '1'), (20, '20'), (100, '100')], default=1, verbose_name='Type de Proche')),
                ('quantite_lot', models.IntegerField(default=0, verbose_name='Quantité du Lot')),
                ('cout_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_entree', models.DateField(default=datetime.date.today)),
                ('quantite_restante', models.IntegerField(default=0)),
                ('id_article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, to='stock_app.article')),
            ],
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('id_depreciation', models.AutoField(primary_key=True, serialize=False)),
                ('date_depreciation', models.DateField()),
                ('montant_depreciation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, to='stock_app.article')),
                ('id_lot', models.ForeignKey(db_column='id_lot', on_delete=django.db.models.deletion.CASCADE, to='stock_app.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement_Entree',
            fields=[
                ('id_entree', models.AutoField(primary_key=True, serialize=False)),
                ('date_entree', models.DateField()),
                ('type_entree', models.CharField(choices=[('achat', 'achat'), ('transfert', 'transfert'), ('retour', 'retour')], max_length=50)),
                ('documents_reglementaires', models.CharField(blank=True, max_length=100, null=True)),
                ('id_article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, to='stock_app.article')),
                ('id_lot', models.ForeignKey(db_column='id_lot', on_delete=django.db.models.deletion.CASCADE, to='stock_app.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement_Sortie',
            fields=[
                ('id_sortie', models.AutoField(primary_key=True, serialize=False)),
                ('date_sortie', models.DateField()),
                ('quantite_sortie', models.IntegerField()),
                ('type_sortie', models.CharField(choices=[('transfert_interne', 'Transfert Interne'), ('consommation_interne', 'Consommation Interne'), ('ajustement', 'Ajustement'), ('destruction', 'Destruction'), ('échantillon', 'Échantillon')], max_length=50)),
                ('valeur_sortie', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, to='stock_app.article')),
                ('id_lot', models.ForeignKey(db_column='id_lot', on_delete=django.db.models.deletion.CASCADE, to='stock_app.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement_Sortie_externe',
            fields=[
                ('id_sortie_externe', models.AutoField(primary_key=True, serialize=False)),
                ('date_sortie', models.DateField()),
                ('quantite_sortie', models.IntegerField()),
                ('type_sortie', models.CharField(choices=[('vente', 'vente'), ('transfert', 'transfert'), ('consommation', 'consommation')], max_length=50)),
                ('documents_reglementaires', models.CharField(blank=True, max_length=100, null=True)),
                ('valeur_sortie', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, to='stock_app.article')),
                ('id_lot', models.ForeignKey(db_column='id_lot', on_delete=django.db.models.deletion.CASCADE, to='stock_app.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Comptage',
            fields=[
                ('id_comptage', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_reel', models.IntegerField()),
                ('ecart_quantite', models.IntegerField(default=0)),
                ('ecart_valeur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_article', models.ForeignKey(db_column='id_article', on_delete=django.db.models.deletion.CASCADE, to='stock_app.article')),
                ('id_inventaire', models.ForeignKey(db_column='id_inventaire', on_delete=django.db.models.deletion.CASCADE, to='stock_app.inventaire')),
            ],
            options={
                'verbose_name': 'Comptage',
                'verbose_name_plural': 'Comptages',
                'unique_together': {('id_inventaire', 'id_article')},
            },
        ),
    ]
