# Generated by Django 5.2.13 on 2026-04-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplacement',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude for map positioning', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='emplacement',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude for map positioning', max_digits=10, null=True),
        ),
    ]
