# Generated by Django 5.2.13 on 2026-04-23 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_emplacement_latitude_emplacement_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Maroc', max_length=100)),
                ('ice', models.CharField(blank=True, max_length=20, null=True, verbose_name='ICE')),
                ('rib', models.CharField(blank=True, max_length=50, null=True)),
                ('categorie', models.CharField(choices=[('matieres_premieres', 'Matières Premières'), ('emballages', 'Emballages'), ('equipements', 'Équipements'), ('services', 'Services'), ('autres', 'Autres')], default='matieres_premieres', max_length=50)),
                ('note', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3)),
                ('delai_livraison_moyen', models.IntegerField(default=7, help_text='Délai moyen en jours')),
                ('taux_qualite', models.DecimalField(decimal_places=2, default=95.0, help_text='Taux de qualité (%)', max_digits=5)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_commande', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fournisseur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateField()),
                ('date_livraison_reelle', models.DateField(blank=True, null=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En Attente'), ('confirmee', 'Confirmée'), ('en_livraison', 'En Livraison'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='stock_app.fournisseur')),
            ],
            options={
                'db_table': 'commande_fournisseur',
            },
        ),
    ]
