# Generated by Django 4.2.7 on 2026-04-26 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0003_fournisseur_commandefournisseur"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comptage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="inventaire",
            options={"ordering": ["-date_inventaire"]},
        ),
        migrations.AlterUniqueTogether(
            name="comptage",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="inventaire",
            name="articles_a_inventorier",
        ),
        migrations.RemoveField(
            model_name="inventaire",
            name="documents_reglementaires",
        ),
        migrations.RemoveField(
            model_name="inventaire",
            name="id_responsable",
        ),
        migrations.RemoveField(
            model_name="inventaire",
            name="statut_inventaire",
        ),
        migrations.RemoveField(
            model_name="inventaire",
            name="type_inventaire",
        ),
        migrations.AddField(
            model_name="inventaire",
            name="article",
            field=models.ForeignKey(
                db_column="id_article",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock_app.article",
                verbose_name="Article inventorié",
            ),
        ),
        migrations.AddField(
            model_name="inventaire",
            name="ecart",
            field=models.IntegerField(default=0, verbose_name="Écart"),
        ),
        migrations.AddField(
            model_name="inventaire",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="inventaire",
            name="quantite_reelle",
            field=models.IntegerField(
                default=0, verbose_name="Quantité réelle (comptée)"
            ),
        ),
        migrations.AddField(
            model_name="inventaire",
            name="quantite_theorique",
            field=models.IntegerField(
                default=0, verbose_name="Quantité théorique (système)"
            ),
        ),
        migrations.AddField(
            model_name="inventaire",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventaire",
            name="statut",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("valide", "Validé"),
                    ("corrige", "Corrigé"),
                ],
                default="brouillon",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventaire",
            name="date_inventaire",
            field=models.DateField(
                auto_now_add=True, verbose_name="Date de l'inventaire"
            ),
        ),
        migrations.AlterModelTable(
            name="inventaire",
            table="inventaire",
        ),
        migrations.RemoveField(
            model_name="comptage",
            name="ecart_quantite",
        ),
        migrations.RemoveField(
            model_name="comptage",
            name="ecart_valeur",
        ),
        migrations.RemoveField(
            model_name="comptage",
            name="id_article",
        ),
        migrations.RemoveField(
            model_name="comptage",
            name="id_inventaire",
        ),
        migrations.RemoveField(
            model_name="comptage",
            name="quantite_reel",
        ),
    ]
