# Generated by Django 6.0.4 on 2026-04-26 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0004_alter_comptage_options_alter_inventaire_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mouvement_entree",
            name="id_responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entrees_effectuees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mouvement_entree",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mouvement_entree",
            name="reference_facture",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mouvement_sortie",
            name="id_responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sorties_effectuees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mouvement_sortie",
            name="motif",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mouvement_sortie",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mouvement_sortie_externe",
            name="client_nom",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mouvement_sortie_externe",
            name="id_responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sorties_externes_effectuees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mouvement_sortie_externe",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HistoriqueEmplacement",
            fields=[
                ("id_historique", models.AutoField(primary_key=True, serialize=False)),
                ("date_debut", models.DateTimeField(auto_now_add=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                ("est_actif", models.BooleanField(default=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock_app.article",
                    ),
                ),
                (
                    "emplacement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="stock_app.emplacement",
                    ),
                ),
            ],
            options={
                "db_table": "historique_emplacement",
                "ordering": ["-date_debut"],
            },
        ),
    ]
