# Generated by Django 6.0.4 on 2026-04-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0005_mouvement_entree_id_responsable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventaire",
            name="commentaire_raison",
            field=models.TextField(
                blank=True, null=True, verbose_name="Commentaire supplémentaire"
            ),
        ),
        migrations.AddField(
            model_name="inventaire",
            name="raison_ecart",
            field=models.CharField(
                blank=True,
                choices=[
                    ("erreur_saisie", "Erreur de saisie"),
                    ("perte_inventaire", "Perte inventoriée"),
                    ("casse", "Casse / Détérioration"),
                    ("vol", "Vol / Disparition"),
                    ("etiquetage", "Erreur d'étiquetage"),
                    ("reception_non_enregistree", "Réception non enregistrée"),
                    ("sortie_non_enregistree", "Sortie non enregistrée"),
                    ("defaut_emballage", "Défaut d'emballage"),
                    ("retour_client", "Retour client non comptabilisé"),
                    ("autre", "Autre"),
                ],
                max_length=50,
                null=True,
                verbose_name="Raison de l'écart",
            ),
        ),
        migrations.AlterField(
            model_name="mouvement_sortie_externe",
            name="type_sortie",
            field=models.CharField(
                choices=[("vente", "vente"), ("consommation", "consommation")],
                max_length=50,
            ),
        ),
    ]
